[project]
name = "tftinfo"
version = "0.1.0"
description = "TFTInfo"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]
